stages:
- lint
- test
- deploy

before_script:
- apt-get update
- apt-get install redis-server -y
- redis-server --daemonize yes
- python -V
- pip install tox

pre-commit-check:
  stage: lint
  image: python:3.6-buster
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pip install pre-commit
    - pre-commit run --all-files

lint-docs:
  stage: lint
  image: python:3.7-buster
  script:
  - tox -e docs

test-36:
  stage: test
  image: python:3.6-buster
  script:
  - tox -e py36
  - bash <(curl -s https://codecov.io/bash)

test-37:
  stage: test
  image: python:3.7-buster
  script:
  - tox -e py37
  - bash <(curl -s https://codecov.io/bash)

test-38:
  stage: test
  image: python:3.8-buster
  script:
  - tox -e py38
  - bash <(curl -s https://codecov.io/bash)

test-39:
  stage: test
  image: python:3.9-buster
  script:
  - tox -e py39
  - bash <(curl -s https://codecov.io/bash)

deploy-pypi:
  stage: deploy
  image: python:3.7-buster

  before_script:
    - pip install twine

  script:
    - python setup.py sdist
    - twine upload dist/*

  only:
    - tags
