# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discord_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='discord_api.proto',
  package='discord_api',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64iscord_api.proto\x12\x0b\x64iscord_api\"\xf9\x01\n\x07\x43hannel\x12\n\n\x02id\x18\x01 \x01(\x04\x12\'\n\x04type\x18\x02 \x01(\x0e\x32\x19.discord_api.Channel.Type\x12\x10\n\x08guild_id\x18\x03 \x01(\x04\x12\x10\n\x08position\x18\x04 \x01(\x05\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\r\n\x05topic\x18\x07 \x01(\t\"x\n\x04Type\x12\x0e\n\nGUILD_TEXT\x10\x00\x12\x0f\n\x0bGUILD_VOICE\x10\x01\x12\x0c\n\x08GROUP_DM\x10\x02\x12\x12\n\x0eGUILD_CATEGORY\x10\x03\x12\x0e\n\nGUILD_NEWS\x10\x04\x12\x0c\n\x08PRODUCTS\x10\x05\x12\x0f\n\x0bGUILD_STORE\x10\x06\"J\n\tThumbnail\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x11\n\tproxy_url\x18\x02 \x01(\t\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\r\n\x05width\x18\x04 \x01(\x05\"V\n\x05\x45mbed\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12)\n\tthumbnail\x18\x03 \x01(\x0b\x32\x16.discord_api.Thumbnail\"_\n\x18SendDirectMessageRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12!\n\x05\x65mbed\x18\x03 \x01(\x0b\x32\x12.discord_api.Embed\"\x1b\n\x19SendDirectMessageResponse\"+\n\x17GetGuildChannelsRequest\x12\x10\n\x08guild_id\x18\x01 \x01(\x04\"B\n\x18GetGuildChannelsResponse\x12&\n\x08\x63hannels\x18\x01 \x03(\x0b\x32\x14.discord_api.Channel2\xd5\x01\n\nDiscordApi\x12\x64\n\x11SendDirectMessage\x12%.discord_api.SendDirectMessageRequest\x1a&.discord_api.SendDirectMessageResponse\"\x00\x12\x61\n\x10GetGuildChannels\x12$.discord_api.GetGuildChannelsRequest\x1a%.discord_api.GetGuildChannelsResponse\"\x00\x62\x06proto3'
)



_CHANNEL_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='discord_api.Channel.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GUILD_TEXT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GUILD_VOICE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GROUP_DM', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GUILD_CATEGORY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GUILD_NEWS', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRODUCTS', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GUILD_STORE', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=164,
  serialized_end=284,
)
_sym_db.RegisterEnumDescriptor(_CHANNEL_TYPE)


_CHANNEL = _descriptor.Descriptor(
  name='Channel',
  full_name='discord_api.Channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='discord_api.Channel.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='discord_api.Channel.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='discord_api.Channel.guild_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='discord_api.Channel.position', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='discord_api.Channel.name', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topic', full_name='discord_api.Channel.topic', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CHANNEL_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=284,
)


_THUMBNAIL = _descriptor.Descriptor(
  name='Thumbnail',
  full_name='discord_api.Thumbnail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='discord_api.Thumbnail.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proxy_url', full_name='discord_api.Thumbnail.proxy_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='discord_api.Thumbnail.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='discord_api.Thumbnail.width', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=360,
)


_EMBED = _descriptor.Descriptor(
  name='Embed',
  full_name='discord_api.Embed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='discord_api.Embed.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='discord_api.Embed.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thumbnail', full_name='discord_api.Embed.thumbnail', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=448,
)


_SENDDIRECTMESSAGEREQUEST = _descriptor.Descriptor(
  name='SendDirectMessageRequest',
  full_name='discord_api.SendDirectMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='discord_api.SendDirectMessageRequest.user_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='discord_api.SendDirectMessageRequest.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='embed', full_name='discord_api.SendDirectMessageRequest.embed', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=545,
)


_SENDDIRECTMESSAGERESPONSE = _descriptor.Descriptor(
  name='SendDirectMessageResponse',
  full_name='discord_api.SendDirectMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=574,
)


_GETGUILDCHANNELSREQUEST = _descriptor.Descriptor(
  name='GetGuildChannelsRequest',
  full_name='discord_api.GetGuildChannelsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='discord_api.GetGuildChannelsRequest.guild_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=576,
  serialized_end=619,
)


_GETGUILDCHANNELSRESPONSE = _descriptor.Descriptor(
  name='GetGuildChannelsResponse',
  full_name='discord_api.GetGuildChannelsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='discord_api.GetGuildChannelsResponse.channels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=621,
  serialized_end=687,
)

_CHANNEL.fields_by_name['type'].enum_type = _CHANNEL_TYPE
_CHANNEL_TYPE.containing_type = _CHANNEL
_EMBED.fields_by_name['thumbnail'].message_type = _THUMBNAIL
_SENDDIRECTMESSAGEREQUEST.fields_by_name['embed'].message_type = _EMBED
_GETGUILDCHANNELSRESPONSE.fields_by_name['channels'].message_type = _CHANNEL
DESCRIPTOR.message_types_by_name['Channel'] = _CHANNEL
DESCRIPTOR.message_types_by_name['Thumbnail'] = _THUMBNAIL
DESCRIPTOR.message_types_by_name['Embed'] = _EMBED
DESCRIPTOR.message_types_by_name['SendDirectMessageRequest'] = _SENDDIRECTMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['SendDirectMessageResponse'] = _SENDDIRECTMESSAGERESPONSE
DESCRIPTOR.message_types_by_name['GetGuildChannelsRequest'] = _GETGUILDCHANNELSREQUEST
DESCRIPTOR.message_types_by_name['GetGuildChannelsResponse'] = _GETGUILDCHANNELSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), {
  'DESCRIPTOR' : _CHANNEL,
  '__module__' : 'discord_api_pb2'
  # @@protoc_insertion_point(class_scope:discord_api.Channel)
  })
_sym_db.RegisterMessage(Channel)

Thumbnail = _reflection.GeneratedProtocolMessageType('Thumbnail', (_message.Message,), {
  'DESCRIPTOR' : _THUMBNAIL,
  '__module__' : 'discord_api_pb2'
  # @@protoc_insertion_point(class_scope:discord_api.Thumbnail)
  })
_sym_db.RegisterMessage(Thumbnail)

Embed = _reflection.GeneratedProtocolMessageType('Embed', (_message.Message,), {
  'DESCRIPTOR' : _EMBED,
  '__module__' : 'discord_api_pb2'
  # @@protoc_insertion_point(class_scope:discord_api.Embed)
  })
_sym_db.RegisterMessage(Embed)

SendDirectMessageRequest = _reflection.GeneratedProtocolMessageType('SendDirectMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDDIRECTMESSAGEREQUEST,
  '__module__' : 'discord_api_pb2'
  # @@protoc_insertion_point(class_scope:discord_api.SendDirectMessageRequest)
  })
_sym_db.RegisterMessage(SendDirectMessageRequest)

SendDirectMessageResponse = _reflection.GeneratedProtocolMessageType('SendDirectMessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDDIRECTMESSAGERESPONSE,
  '__module__' : 'discord_api_pb2'
  # @@protoc_insertion_point(class_scope:discord_api.SendDirectMessageResponse)
  })
_sym_db.RegisterMessage(SendDirectMessageResponse)

GetGuildChannelsRequest = _reflection.GeneratedProtocolMessageType('GetGuildChannelsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETGUILDCHANNELSREQUEST,
  '__module__' : 'discord_api_pb2'
  # @@protoc_insertion_point(class_scope:discord_api.GetGuildChannelsRequest)
  })
_sym_db.RegisterMessage(GetGuildChannelsRequest)

GetGuildChannelsResponse = _reflection.GeneratedProtocolMessageType('GetGuildChannelsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETGUILDCHANNELSRESPONSE,
  '__module__' : 'discord_api_pb2'
  # @@protoc_insertion_point(class_scope:discord_api.GetGuildChannelsResponse)
  })
_sym_db.RegisterMessage(GetGuildChannelsResponse)



_DISCORDAPI = _descriptor.ServiceDescriptor(
  name='DiscordApi',
  full_name='discord_api.DiscordApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=690,
  serialized_end=903,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendDirectMessage',
    full_name='discord_api.DiscordApi.SendDirectMessage',
    index=0,
    containing_service=None,
    input_type=_SENDDIRECTMESSAGEREQUEST,
    output_type=_SENDDIRECTMESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetGuildChannels',
    full_name='discord_api.DiscordApi.GetGuildChannels',
    index=1,
    containing_service=None,
    input_type=_GETGUILDCHANNELSREQUEST,
    output_type=_GETGUILDCHANNELSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISCORDAPI)

DESCRIPTOR.services_by_name['DiscordApi'] = _DISCORDAPI

# @@protoc_insertion_point(module_scope)
